[package]
name = "barycenter-parallel"
version = "0.1.0"
authors = ["Eduard Luhtonen <luhtonen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
rayon = "1.3.0"
